### ISSUE TITLE
Create model tables

### ISSUE THREAD

**Issue by haijamee** [jcsdmi/Beauty-Book#10]
EXAMPLE:
Post

| Property      | Type          | Description |
| ------------- |-------------  | ----- |
| object        | String        | Unique id for the user post   
| author        | Pointer to user| Image author     
| image         | file          | Image file the user post 
| Caption       | String        | Image caption by author
| commentsCount | int           | Number of comments that has been posted
| location      | JSON          | Stores the location of the user
| object        | String        | Unique id for the user post
| likesCount    | int           | Number of likes for the post
| Created_at    | DateTime      | Date when post is created (default)
| Updated_at    | DateTime      | Date when post is last created (default)
| rating        | double        | A value that holds the rating

**Comment by Zarsla** [comment]
## Schema 
### Models
#### Profiles

   | Property      		  | Type                | Description |
   | ---------------------| --------------------| ----------------------------------------------------------|
   | profileId     		  | String              | unique id for the user profile 						  	|
   | username     		  | String              | string that is the username    						  	|
   | password     		  | String              | string that is the password    						  	|   
   | profileImage         | File                | image for the user profile     						  	|
   | profileDescription   | String              | Bio/text details about te user 						  	|
   | profileFollower      | Array 	| array of pointers to people who are following the user 	|
   | following     		  | Array   | array of pointers to people who are followed by the user  |

#### Guide

   | Property           | Type     		   | Description |
   | -------------------| -----------------| -----------------------------------------------------------------|
   | guideId            | String   		   | unique id for the user post (default field) 	  				  |
   | guideTitle         | String 		   | Title For guide(default field)  			 					  |
   | guideDescription   | String 		   | Description for guide(default field) 						 	  |
   | guideImage         | File     		   | image that user posts 						  					  |
   | guideCreator       | Pointer to Profile | Pointer to the Profile of Creator of Guide				      |
   | guideLearners      | Array            | Array of Pointers to the Users who selected guide to learn from  |
   | guideLikes         | Array   		   | Array of the Likes objects					   					  |
   | instruction        | Array  		   | Array of the Instruction objects    			  				  |
   | tags		        | Array  		   | Array of the strings. Strings can be searched for.				  |
   | createdAt          | DateTime 		   | date when post is created (default field) 	  					  |
   | updatedAt     		| DateTime 		   | date when post is last updated (default field) 				  |

#### Instruction

   | Property      		  | Type     		 | Description 										 |
   | ---------------------| -----------------| --------------------------------------------------|
   | instructId    		  | String   		 | unique id for the instructor post (default field) |
   | guide         		  | Pointer to Guide | pointer to the guide 							 |
   | instuctImage         | File     		 | image for instrcutions 							 |
   | instructDescription  | String   		 | text instructions 								 |


#### Likes

   | Property      | Type     		 | Description 									|
   | ------------- | ----------------| ---------------------------------------------|
   | likeId    	   | String   		 | unique id for the like (default field) 		|
   | isLiked       | Boolean		 | Like value. True = Like, False = Disliked	|
   | liker         | Pointer to Profile | Pointer to the user who liked this			|

**Comment by Zarsla** [comment]
Here's the models, I'm not sure how to post it on to the model.

**Comment by haijamee** [comment]
Can't you copy and paste what you did up there?
